# Site settings
baseurl = "https://kentasuzuki.net/"
languageCode = "ja-JP"
title = "kentasuzuki.net"
theme = "hugo-artists-theme"

[params]
	name = "Kenta Suzuki"
	description = "Your description"
	email = ""

	# Header an navigation
	#
	# To change the header background the 'hero-bg.jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "kentasuzuki.net"
		shortBio = "Programmer / Sunday Guitarist / Podcaster"

	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About me"
		bio = "北海道十勝出身、東京在住のソフトウェアエンジニアです。プログラミングと音楽とビールが好きです。日曜日はだいたいクラシックギターを弾いています。"
        long = """
## 読みもの・聴きもの

ブログや本を書いたりポッドキャストで話したりしています。

* 技術的な話はこちら: [すずけんメモ](http://suzuken.hatenablog.jp)
* 音楽やエッセイ的なものはこちら: [Source](http://blog.kentasuzuki.net)
* [ajitofm](https://ajito.fm/) という技術系の話題に特化したポッドキャストをやっています。 [iOS](https://itunes.apple.com/jp/podcast/ajitofm/id1257346086?l=ja) / [Android](https://www.subscribeonandroid.com/ajito.fm/index.xml)

## エンジニアリングについて

主に次のことをやっています。

* インターネット広告事業に関わるプロダクト戦略づくり
* データ分析基盤構築
* レガシーなソフトウェアの継続改善
* API設計と構築、データ基盤設計構築
* プログラミング教育

## 時系列

プログラミングを始めたのは大学に入ってからです。アルバイトをしたり、研究をしながら学びました。2011年2月ごろから[trippiece](http://trippiece.com/)の立ち上げをやっていました。その頃の様子は以下の記事などをみると伝わるかと思います。

* [Source: Trippieceプレリリースと、反省と。](http://blog.kentasuzuki.net/2011/05/trippiece.html)
* [Source: trippiece α リリース、または、シードベンチャーでのエンジニアリングについて](http://blog.kentasuzuki.net/2011/08/trippiece.html)
* [Source: デザインから逃げない](http://blog.kentasuzuki.net/2011/09/blog-post.html)
* [Source: 卒業と退職](http://blog.kentasuzuki.net/2012/04/blog-post.html)
* [[連載：NEOジェネ！] 旅のソーシャルWeb『trippiece』が4度目の改変で気付いた「最強チームのつくり方」 - エンジニアtype](http://engineer.typemag.jp/article/trippiece)

[慶應義塾大学理工学研究科の山口研究室](http://www.yamaguti.comp.ae.keio.ac.jp)でセマンティックWebに関わる研究をしていました。内容は会計のデータをどのようにオントロジーとして表現し、共有するか、ということです。データのモデリングからシステムの設計構築までを担当しました。

JSAI2012の資料: [大規模会計 Linked Data のためのシステムアーキテクチャ](https://kaigi.org/jsai/webprogram/2012/pdf/479.pdf)

2012年からは [株式会社VOYAGE GROUP](http://voyagegroup.com/) でアドテクノロジー領域の開発に携わっています。広告データの解析基盤の構築や、ターゲティングの仕組みの開発、及び広告配信に関わる領域についての開発をしていました。現在はSSP事業の開発全般に携わっています。それに付随して、開発環境の整備や、サーバの管理などについても担当することもあります。

また、2014年にはログ解析に関する本を書きました。2017年に改訂されています。私の章ではなぜログ解析を行う必要があるのか。そしてどのような選択肢があり、どのように方法を選択していけばよいのか、という観点から書いています。

* [サーバ/インフラエンジニア養成読本 ログ収集~可視化編 を書きました - すずけんメモ](http://suzuken.hatenablog.jp/entry/2014/07/18/084555)
* 出版イベントでの導入資料です。: [サービス改善はログデータ分析から](http://www.slideshare.net/suzuken/ss-38865046)
* 2017年9月に [データ分析基盤構築入門 (Fluentd，Elasticsearch，Kibanaによるログ収集と可視化)](http://gihyo.jp/book/2017/978-4-7741-9218-5) として再構成し、出版しました。

2014年からVOYAGE GROUPのソフトウェアエンジニア学生向けインターンTreasureの講師も務めています。2016年からはGoに関する講義とインターン全体の技術領域におけるプランニングをしています。

2015年からは何かあればだいたいGoで書くようになりました。その流れで2016年9月に「みんなのGo言語」という本を出しました。私はテストに関する章を書きました。

* [みんなのGo言語](http://gihyo.jp/book/2016/978-4-7741-8392-3)
* [「みんなのGo言語」の執筆に参加しました](http://suzuken.hatenablog.jp/entry/2016/08/08/132303)

2016年にエンジニアリングについてインタビューを受けました。

* [スタートアップでのCTO経験で学んだ、エンジニアに必要な「経営的視点」－fluct 鈴木健太（suzuken）氏](http://press.forkwell.com/post/149349743522/interview-suzuken)

## 発表資料 / 動画

* 2012年夏、解析環境の整備をしていたころの資料です: [Jenkinsとhadoopを利用した継続的データ解析環境の構築](http://www.slideshare.net/suzuken/jenkinshadoop)
* 2013年、アドテクノロジー領域、とくにDMPと言われている領域について説明した資料です: [Head First Ad Technology and DMP](http://www.slideshare.net/suzuken/head-first-ad-technology-and-dmp)
* 2014年、AWSを利用したデータ解析基盤の構築について発表した資料です。: [Data Stream Processing and Analysis on AWS #awscasual](http://www.slideshare.net/suzuken/data-stream-processing-and-analysis-on-aws-awscasual)
* 2015年春、JAWS DAYS 2015でデータエンジニアリングについて発表した時の資料です。: [Data Engineering at VOYAGE GROUP #jawsdays](http://www.slideshare.net/suzuken/data-engineering-atvoyagegroupjawsdays2015)
* 2016年4月、[http2study](https://http2study.connpass.com/event/29813/)で [ディスプレイ広告の基礎とセキュリティ](https://speakerdeck.com/suzuken/deisupureiguang-gao-falseji-chu-tosekiyuritei) について話しました。
* 2016年6月、AWS Summit Tokyo Developer Conferenceで「サーバレスの波はホンモノか？」のパネルディスカッションに登壇しました。 [http://suzuken.hatenablog.jp/entry/2016/06/02/184723](http://suzuken.hatenablog.jp/entry/2016/06/02/184723)
* 2017年8月、エンジニア学生向けインターンTreasureでのGo言語入門資料です。 [Go入門](https://go-talks.appspot.com/github.com/voyagegroup/talks/2017/treasure-go/intro.slide#1) 紹介記事: [Treasure 2017 の研修資料は Go を学ぶのに最高だった - kakakakakku blog](https://kakakakakku.hatenablog.com/entry/2017/10/16/081755)
* 2017年10月、PHPカンファレンス2017で [
広告配信管理システムを支えるPHP - レガシーシステムからの段階的移行戦略](https://speakerdeck.com/suzuken/phpcon2017) というテーマで発表しました。
* 2018年4月、ITP Studyで[ディスプレイ広告とITP](https://go-talks.appspot.com/github.com/suzuken/talks/2018-itpstudy/itp.slide#1)について話しました。
* 2019年1月、[次世代 Web カンファレンス - connpass](https://nextwebconf.connpass.com/event/103056/)のAdセッションでオーナーをしました。ITP, GDPR, セキュリティをはじめ、広告に関連する様々なトピックについて80分議論しています。 [動画: Ad - 次世代Webカンファレンス #nwc_ad - YouTube](https://www.youtube.com/watch?v=CBBh_qRYRcE&t=3s)

他の発表資料はSlideShareやSpeckerDeckでも見ることができます: [SlideShare](http://www.slideshare.net/suzuken) / [Speaker Deck](https://speakerdeck.com/suzuken) / [suzuken/talks](https://github.com/suzuken/talks)

"""

	# Contact secion
	[params.contact]
		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/suzu_v"

		[[params.contact.social]]
			icon = "github"
			link = "//github.com/suzuken"

		[[params.contact.social]]
			icon = "youtube"
			link = "//www.youtube.com/kentasuzukinet"

	[params.footer]
		copyright = "2018 Kenta Suzuki all rights reserved."
