baseurl = "http://kentasuzuki.net"
languageCode = "ja"
title = "kentasuzuki.net"

[params]
ProfilePicture = "https://instagram.com/p/1ouXT1r_Jk/media/?size=m"
AuthorName = "Kenta Suzuki"
Description = "Web site of Kenta Suzuki"
Copyright = "Kenta Suzuki"

[params.index]
TopPicture = "img/top.jpg"

[params.links]
Home = "/"
About = "/about/"

[params.social]
github      = "suzuken"
facebook        = "suzuken326"
# facebook_admin  = "17807199"
twitter     = "suzu_v"
pinterest       = "suzuken"
instagram       = "suzuken"
youtube         = "suzuken"

[taxonoies]
tag = "tags"
category = "categories"
