baseurl: "http://kentasuzuki.net"
languageCode: "ja"
title: "kentasuzuki.net"
params:
  ProfilePicture: "https://avatars2.githubusercontent.com/u/491428?v=3&s=460"
  AuthorName: "Kenta Suzuki"
  Description: "Web site of Kenta Suzuki"
  links:
    Home: "/"
    Blog: "/blog/"
    About: "/about/"
  Copyright: "Kenta Suzuki"
